spring:
  application:
    name:
      wheelly
  datasource:
    url: jdbc:postgresql://localhost:5432/WHEELLY
    username: springboot
    password: springboot
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true